name: Build and Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #python-version: [ "3.7", "3.8", "3.9"]
        #os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [ "3.8" ]
        os: [windows-latest]
        #platform: [x64, x32]
        platform: [x64]
        exclude:
          - os: macos-latest  
            platform: x32
    steps:
    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} numpy cython pip pytest hdf5 libnetcdf cftime --strict-channel-priority
        source activate TEST
        export PATH="$CONDA_PREFIX/bin:$PATH" # so setup.py finds nc-config
        cd $CONDA_PREFIX
        find ./ -name 'hdf5.h' -print
        find ./ -name 'nc-config' -print
        ls -l $CONDA_PREFIX
        ls -l $CONDA_PREFIX/Scripts
        ls -l $CONDA_PREFIX/DLLs
        pip install -e . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Tests
      shell: bash -l {0}
      run: |
        source activate TEST
        cd test && python run_all.py
