name: Build and Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run-serial:
    runs-on: ${{ matrix.os }}
    #env:
    #  NO_NET: 1
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
        os: [windows-latest, ubuntu-latest, macos-latest]
        platform: [x64, x32]
        exclude:
          - os: macos-latest  
            platform: x32
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@v13
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=${{ matrix.python-version }} numpy cython pip pytest hdf5 libnetcdf cftime zlib --channel conda-forge
        micromamba activate TEST
        export PATH="${CONDA_PREFIX}/bin:${CONDA_PREFIX}/Library/bin:$PATH" # so setup.py finds nc-config
        pip install -v -v -v -e . --no-deps --force-reinstall

    - name: Debug conda
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        micromamba info --all
        micromamba list

    - name: Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        cd test && python run_all.py

  run-mpi:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.10" ]
        os: [ubuntu-latest]
        platform: [x64]
    steps:
    - uses: actions/checkout@v2

    - name: Setup Micromamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: false

    - name: Python ${{ matrix.python-version }}
      shell: bash -l {0}
      run: |
        micromamba create --name TEST python=${{ matrix.python-version }} numpy cython pip pytest mpi4py hdf5=*=mpi* libnetcdf=*=mpi* cftime zlib --channel conda-forge
        micromamba activate TEST
        export PATH="${CONDA_PREFIX}/bin:${CONDA_PREFIX}/Library/bin:$PATH" # so setup.py finds nc-config
        nc-config --all
        mv pyproject.toml pyproject.toml.save
        pip install -v -v -v -e . --no-deps --force-reinstall

    - name: Debug conda
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        micromamba info --all
        micromamba list

    - name: Tests
      shell: bash -l {0}
      run: |
        micromamba activate TEST
        cd test && python run_all.py
        cd ../examples
        export PATH="${CONDA_PREFIX}/bin:${CONDA_PREFIX}/Library/bin:$PATH" 
        which mpirun
        mpirun --version
        mpirun -np 4 --oversubscribe python mpi_example.py # for openmpi
        #mpirun -np 4 python mpi_example.py
        if [ $? -ne 0 ] ; then
          echo "hdf5 mpi test failed!"
          exit 1
        else
          echo "hdf5 mpi test passed!"
        fi
